[application]
asset_dir = "assets"
out_dir = "../../.generated/builds"

[bundle]
identifier = "mx.virgensystems.formo"
publisher = "virgensystems"

[android]
min_sdk = 33
target_sdk = 36

[ios]
deployment_target = "16.0"
